	if($(window).width()>768){
  $(document).ready(function(){
  $("#placement").mouseover(function(){
  $(".placementsub").show(200);
  $("#placement").mouseleave(function(){
  $(".placementsub").hide(250);
  });
  });
  });}
  if($(window).width()>768){
  $(document).ready(function(){
  $("#training").mouseover(function(){
  $(".trainingsub").show(200);
  $("#training").mouseleave(function(){
  $(".trainingsub").hide(250);  
  });
  });
  });}
    if($(window).width()>768){
  $(document).ready(function(){
  $("#academic").mouseover(function(){
  $(".academicsub").show(200);
  $("#academic").mouseleave(function(){
  $(".academicsub").hide(250);  
  });
  });
  });}